# Generated by Django 6.0.6 on 2026-06-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_chatmessage_attachment_type_chatmessage_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Todo.chatmessage'),
        ),
    ]
